name: CI

on:
  push:
    branches: 
     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet ./...

      - name: Install StaticCheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1

      - name: StaticCheck
        run: staticcheck ./...

      - name: Test
        run: go test -covermode=count -coverprofile=coverage.txt -v ./...

      - name: Build
        run: go build -v ./...

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/smoretto/app:latest
          push: true
